# Generated by Django 6.0.5 on 2026-05-26 12:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True)),
                ('source', models.CharField(choices=[('ONLINE', 'Online'), ('ONSITE', 'Onsite')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('EXPIRED', 'Expired'), ('CANCELED', 'Canceled')], max_length=20)),
                ('total_amount', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('FOOD', 'Food'), ('DRINK', 'Drink'), ('COMBO', 'Combo'), ('MERCHANDISE', 'Merchandise'), ('OTHER', 'Other')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('grid_rows', models.PositiveIntegerField()),
                ('grid_cols', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudioType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('base_price', models.PositiveIntegerField()),
                ('picture', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('synopsis', models.TextField()),
                ('age_rating', models.CharField(choices=[('ALL_AGE', 'Semua Usia'), ('R7', 'R7+'), ('R13', 'R13+'), ('R17', 'R17+'), ('R21', 'R21+')], max_length=20)),
                ('main_picture', models.CharField(blank=True, max_length=255)),
                ('runtime_minutes', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('movie_theme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.movietheme')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='OrderCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='cinema.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.PositiveIntegerField()),
                ('total_price', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='cinema.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.product')),
            ],
        ),
        migrations.CreateModel(
            name='ShowTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('end_at', models.DateTimeField()),
                ('price', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.movie')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.studio')),
            ],
            options={
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=12)),
                ('row', models.CharField(max_length=4)),
                ('grid_x_pos', models.PositiveIntegerField()),
                ('grid_y_pos', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='cinema.studio')),
            ],
            options={
                'ordering': ['studio', 'grid_y_pos', 'grid_x_pos'],
            },
        ),
        migrations.AddField(
            model_name='studio',
            name='studio_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.studiotype'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('HELD', 'Held'), ('CONFIRMED', 'Confirmed'), ('EXPIRED', 'Expired'), ('CANCELED', 'Canceled'), ('PRINTED', 'Printed')], max_length=20)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='cinema.order')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.seat')),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='cinema.showtime')),
            ],
            options={
                'ordering': ['showtime', 'seat__grid_y_pos', 'seat__grid_x_pos'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_payment_id', models.CharField(max_length=32, unique=True)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=32)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('EXPIRED', 'Expired'), ('REFUND_PENDING', 'Refund Pending'), ('REFUNDED', 'Refunded'), ('CANCELED_BEFORE_PAID', 'Canceled Before Paid')], max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('payment_url', models.CharField(blank=True, max_length=255)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='cinema.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='cinema_paym_status_fa22b7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='showtime',
            index=models.Index(fields=['studio', 'start_at', 'end_at'], name='cinema_show_studio__4bc591_idx'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('studio', 'number'), name='unique_seat_number_per_studio'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('studio', 'grid_x_pos', 'grid_y_pos'), name='unique_seat_position_per_studio'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['HELD', 'CONFIRMED', 'PRINTED'])), fields=('showtime', 'seat'), name='unique_active_ticket_per_showtime_seat'),
        ),
    ]
