# Generated by Codex on 2026-05-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="va_account",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
