# Generated by Codex on 2026-05-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0002_payment_va_account"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="source",
            new_name="channel",
        ),
        migrations.AlterField(
            model_name="order",
            name="channel",
            field=models.CharField(
                choices=[
                    ("ONLINE", "Online"),
                    ("ONSITE", "Onsite"),
                ],
                max_length=10,
            ),
        ),
    ]
