# Generated by Codex on 2026-05-27

import uuid

from django.db import migrations, models
from django.db.models import Q


def migrate_printed_tickets(apps, schema_editor):
    Ticket = apps.get_model("cinema", "Ticket")
    for ticket in Ticket.objects.filter(status__in=["CONFIRMED", "PRINTED"]):
        updates = []
        if ticket.status == "PRINTED":
            ticket.status = "CONFIRMED"
            updates.append("status")
        if ticket.qr_identifier is None:
            ticket.qr_identifier = uuid.uuid4()
            updates.append("qr_identifier")
        if updates:
            ticket.save(update_fields=updates)


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0003_rename_order_source_to_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="qr_identifier",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.RunPython(migrate_printed_tickets, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="ticket",
            name="unique_active_ticket_per_showtime_seat",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="printed_at",
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("HELD", "Held"),
                    ("CONFIRMED", "Confirmed"),
                    ("USED", "Used"),
                    ("EXPIRED", "Expired"),
                    ("CANCELED", "Canceled"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                condition=Q(("status__in", ["HELD", "CONFIRMED", "USED"])),
                fields=("showtime", "seat"),
                name="unique_active_ticket_per_showtime_seat",
            ),
        ),
    ]
