# Generated by Django 6.0.5 on 2026-05-28 03:34

import cinema.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='main_picture',
            field=models.ImageField(blank=True, storage=cinema.models.OverwriteMovieImageStorage(), upload_to=cinema.models.movie_main_picture_upload_to),
        ),
    ]
