# Generated by Django 6.0.5 on 2026-05-28 05:13

import cinema.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_alter_movie_main_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, storage=cinema.models.OverwriteMovieImageStorage(), upload_to=cinema.models.product_picture_upload_to),
        ),
    ]
