# Generated by Django 6.0.5 on 2026-05-26 12:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_payment_id', models.CharField(max_length=32, unique=True)),
                ('internal_payment_id', models.CharField(max_length=32)),
                ('client_id', models.CharField(default='SILVERSCREEN', max_length=80)),
                ('amount', models.PositiveIntegerField()),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiration_in', models.PositiveIntegerField(default=900)),
                ('expired_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('WAITING_PAYMENT', 'Menunggu Bayar'), ('PAID', 'Paid'), ('EXPIRED', 'Expired')], default='WAITING_PAYMENT', max_length=20)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
