# Generated by Codex on 2026-05-27

from django.db import migrations, models


def backfill_va_accounts(apps, schema_editor):
    GatewayPayment = apps.get_model("stub_payment_gateway", "GatewayPayment")
    for index, payment in enumerate(GatewayPayment.objects.order_by("id"), start=1):
        if not payment.va_account:
            payment.va_account = f"88080000{index:08d}"
            payment.save(update_fields=["va_account"])


class Migration(migrations.Migration):

    dependencies = [
        ("stub_payment_gateway", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gatewaypayment",
            name="va_account",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.RunPython(backfill_va_accounts, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="gatewaypayment",
            name="va_account",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
