# Generated by Codex on 2026-05-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stub_payment_gateway", "0002_gatewaypayment_va_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="gatewaypayment",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
