# Generated by Codex on 2026-05-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stub_payment_gateway", "0003_gatewaypayment_paid_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gatewaypayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("WAITING_PAYMENT", "Menunggu Bayar"),
                    ("PAID", "Paid"),
                    ("EXPIRED", "Expired"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="WAITING_PAYMENT",
                max_length=20,
            ),
        ),
    ]
